### ISSUE TITLE
User mit Benutzerrolle ohne jeglicher Berechtigung hat Zugriff auf TeamStream

### ISSUE THREAD

**Issue by lionstone1** [TeamGrid/bugtracker#10]
Ich habe einen Nutzer angelegt welcher eine Benutzerrolle zugewiesen bekommen hat, in welcher er keine einzige Berechtigung hat und trotzdem hat dieser Nutzer die Möglichkeit über den TeamStream im Notifications-Panel alle Aktivitäten aller Nutzer nachzuvollziehen.

**Comment by maxnowack** [comment]
Dies ist korrekt. Allerdings ist der Team-Stream security-trimmed. Das bedeutet, dass der Benutzer nur die Aktionen sieht, wird die er auch die nötige Berechtigung hat. Dies greift nach dem ändern der Benutzerrolle erst, sobald der Nutzer die Seite neugeladen hat und nicht direkt, wie in vielen anderen Teilen von TeamGrid.
Wenn nach dem Reload trotzdem noch Inhalte im Team-Stream zu sehen sind, die eigentlich nicht sichtbar sein sollten, ist das ein Fehler.
Ist dies bei dir der Fall?

**Comment by lionstone1** [comment]
Ja das ist momentan noch der Fall. Mein Testuser hat keine Berechtigung und ist für kein Projekt freigeschaltet und trotzdem kann dieser momentan noch Beträge, Mitarbeiter und Kunden über den Team-Stream einsehen.

**Comment by maxnowack** [comment]
Welche sind das denn konkret? Gerne auch als Screenshot an support@teamgridapp.com

**Comment by lionstone1** [comment]
Hier wären ein paar Beispiele welche der User über den notifications-teamstream sehen kann:
[ADMINISTRATOR] änderte den Stundensatz für den Kunden [XYZ] auf [X€]
[MITARBEITER] erstellte das Unternehmen [UNTERNEHMEN]
[ADMINISTRATOR] hat den Abrechnungstyp des Kunden [UNTERNEHMEN] zu Hourly rate geändert
[ADMINISTRATOR] entfernte die Abrechnungseinstellungen des Kunden [UNTERNEHMEN]
usw.

**Comment by maxnowack** [comment]
Ein Fix für den Bug wird heute Abend deployed :)
