### ISSUE TITLE
Aufrufen von Einstellungsseiten möglich trotz fehlender Berechtigung

### ISSUE THREAD

**Issue by lionstone1** [TeamGrid/bugtracker#13]
Es ist möglich trotz fehlender Berechtigung auf Einstellungsseiten zuzugreifen wenn man den Link besitzt. Das bedeutet z.B. dass es möglich ist alle Benutzerrollen mit allen Einstellungen anzuzeigen obwohl einem die Berechtigung hierfür fehlt.

Beispiel-Link: https://my.teamgridapp.com/[COMPANY]/settings/team/roles
Dieser Link lässt sich immer aufrufen, unabhängig von der Benutzerrollen-Einstellung.

**Comment by maxnowack** [comment]
Danke für die Meldung des Fehlers. Wird behoben :)

**Comment by maxnowack** [comment]
Ein Fix für den Bug wird heute Abend deployed :)
