### ISSUE TITLE
Adress-Link hat fehlerhafte Parameter > Karte öffnet nicht

### ISSUE THREAD

**Issue by jostange** [TeamGrid/bugtracker#15]
Die Adresse von Kontakten ist verlinkt. Ein Klick versucht Apple Karten zu öffnen. Leider sind alle Parameter mit "undefined" bestückt und die Adresse kann nicht geladen werden.
Feature-Request dazu wäre, dass man in den EInstellungen zwischen Apple Karten und Google Maps wählen kann.

![bildschirmfoto 2018-03-09 um 10 18 56](https://user-images.githubusercontent.com/30128987/37200113-1bfd47fe-2384-11e8-8b6d-1d7461ce6544.png)
![bildschirmfoto_2018-03-09_um_10_18_38](https://user-images.githubusercontent.com/30128987/37200114-1c1ebe98-2384-11e8-8400-ae53197bd75e.png)
![bildschirmfoto_2018-03-09_um_10_18_46](https://user-images.githubusercontent.com/30128987/37200115-1c39d386-2384-11e8-9844-0097d172951f.png)

**Comment by maxnowack** [comment]
Inzwischen behoben
