### ISSUE TITLE
Grammatikalischer Fehler im Bestätigungsdialog zum Löschen von Kommentaren

### ISSUE THREAD

**Issue by milvusz** [TeamGrid/bugtracker#16]
Nicht direkt ein Bug, aber daher bestimmt auch einfach zu beheben … Wenn man einen Kommentar löschen möchte, öffnet sich ein Bestätigungsdialog. Dort steht „dieses Kommentar“; allerdings müsste es hier „diesen Kommentar“ heißen, denn es ist „DER Kommentar“, nicht „das“. Danke.

![bildschirmfoto 2018-12-12 um 12 42 03](https://user-images.githubusercontent.com/44051609/49872542-b179ff00-fe19-11e8-9761-389b46f829b8.png)

**Comment by maxnowack** [comment]
Danke für den Hinweis! Ist behoben und wird heute Abend auf das Produktivsystem gespielt 😉
