### ISSUE TITLE
Value 0 in der Summierung unter Analytics>Projekte

### ISSUE THREAD

**Issue by jostange** [TeamGrid/bugtracker#2]
In der Projekte-Ansicht werden Zeiten, Umsatz und Gewinn nicht summiert sondern mit 0 ausgegeben. Der Fehler tritt auf bei: Projekte, Kunden, Leistungen.
Korrekt addiert wird unter Benutzer, Zeiten

![bildschirmfoto_2017-07-12_um_22_30_47](https://user-images.githubusercontent.com/30128987/28138919-b992a4e4-6752-11e7-8937-fd5becf45a58.png)

**Comment by maxnowack** [comment]
Vielen Dank für die Bug-Meldung. Der Fehler ist behoben und wird mit dem nächsten Release im Laufe des Tages deployed :)
