### ISSUE TITLE
Pagebrowser in Analytics > Projekte nicht sichtbar

### ISSUE THREAD

**Issue by jostange** [TeamGrid/bugtracker#3]
Wenn man in den Projekte View wechselt werden bei einer größeren Anzahl an Projekten nicht alle Projekte angezeigt. Der Pagebrowser am Ende zeigt nur "letzte". Damit kann man nicht alle Projekte anzeigen lassen.

**Comment by maxnowack** [comment]
Der Bug ist behoben und wird mit dem nächsten Release deployed. Vielen Dank für die Meldung 👍
