### ISSUE TITLE
Unerwartetes Verhalten bei archivierten Projekten

### ISSUE THREAD

**Issue by jostange** [TeamGrid/bugtracker#4]
1. Klick auf Projekte
2. Suche nach Projektnamen
3. Wechsel in Archivierte Projekte
4. Projekt anklicken
5. „zurück“-Button betätigen (Action icon : icon-arrange-3-4)

**> Listenansicht in archivierte Projekte mit ungefilterten Projekten <**

![01](https://user-images.githubusercontent.com/30128987/28412368-507373f6-6d44-11e7-9c5a-82c42d9f9dd2.png)
![02](https://user-images.githubusercontent.com/30128987/28412367-50718d70-6d44-11e7-98e1-d8a4fb0b9f01.png)
![03](https://user-images.githubusercontent.com/30128987/28412366-5070671a-6d44-11e7-90c7-988c4969eb6e.png)
![04](https://user-images.githubusercontent.com/30128987/28412369-5075e9b0-6d44-11e7-9546-400404599f1b.png)

**Comment by maxnowack** [comment]
Danke für die Meldung. Wir haben den Fehler behoben und deployen gleich eine neue Version
