### ISSUE TITLE
Zugeordnetes Projekt erscheint nicht unter "Meine Projekte"

### ISSUE THREAD

**Issue by jostange** [TeamGrid/bugtracker#5]
Es kommt vor, dass Projekte in der Übersicht eines Benutzers nicht in der Ansicht "Meine Projekte" auftauchen, obwohl es im Projekt eine Aufgabe gibt, die diesem Benutzer zugeordnet ist.
Die Vermutung, dass Projekte nur dann in der Übersicht auftauchen, wenn auch Zeit darauf erfasst wurde, hat auch nicht gestimmt.
<img width="598" alt="1" src="https://user-images.githubusercontent.com/30128987/29767176-c892aaa8-8be1-11e7-8ba0-e2ac057e23f0.png">
<img width="601" alt="2" src="https://user-images.githubusercontent.com/30128987/29767177-c8936cd6-8be1-11e7-8430-55d8c343de62.png">
<img width="1123" alt="3" src="https://user-images.githubusercontent.com/30128987/29767178-c8948c88-8be1-11e7-9391-0f5cb7ed171a.png">
<img width="1112" alt="4" src="https://user-images.githubusercontent.com/30128987/29767179-c89a62e8-8be1-11e7-834a-a559ff583159.png">

**Comment by maxnowack** [comment]
Wird mit dem nächsten Release behoben
