### ISSUE TITLE
Neu angelegte Projekte laden nicht nach Speichern

### ISSUE THREAD

**Issue by jostange** [TeamGrid/bugtracker#6]
Wenn ein Projekt neu angelegt wird, aktualisiert sich die Anzeige manchmal nicht (der Loader lädt und lädt). Ein Refresh bringt einen dann zur erwarteten Ansicht.

Diese JS-Fehler werden ausgegeben:
api-iam.intercom.io/messenger/web/events Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
tasks:1 Uncaught (in promise) {"type":"error.list","request_id":"auglfc17r2pv4eqf1ou0","errors":[{"code":"422","message":"Cannot have more than 120 active event names"}]}

**Comment by maxnowack** [comment]
Dieser Fehler sollte in der Zwischenzeit behoben worden sein. Bitte melden, falls der Fehler dennoch auftritt.
Die Fehlermeldung hat mit dem mit dem ursprünglichen Fehler leider nichts zu tun :-/
