### ISSUE TITLE
Falscher Projekttitel bei Aufgaben nach Umbenennung des Projektes

### ISSUE THREAD

**Issue by jostange** [TeamGrid/bugtracker#7]
Wird ein Projekt umbenannt, scheint das in der Ansicht unter "Meine Aufgaben" nicht (gleich) aktualisiert zu werden. Hier steht nach wie vor der "alte" Projekttitel

![bildschirmfoto_2017-10-12_um_15_48_34](https://user-images.githubusercontent.com/30128987/31499506-4ae87c0c-af65-11e7-9dbf-00a6bee0ea11.png)

**Comment by maxnowack** [comment]
Wird mit dem nächsten Release behoben
