### ISSUE TITLE
Fälligkeitsreminder trotz abgeschlossener Aufgabe

### ISSUE THREAD

**Issue by jostange** [TeamGrid/bugtracker#8]
Mitarbeiter bekommen Reminder zum Fälligkeitsdatum per Mail über Aufgaben, die bereits abgeschlossen sind. Sogar abgeschlossene Aufgaben, die in einem abgeschlossenem (aber noch nicht archiviertem) Projekt liegen, schicken Reminer.

**Comment by maxnowack** [comment]
@jostange den Fehler konnte ich im Code nicht nachvollziehen. Kannst du mir mal eine Task-Id schicken, wenn das Phänomen nochmal auftritt? Am besten über den Support-Chat oder per Mail an support@teamgridapp.com
